### ISSUE TITLE
NRSur7dq4 BUG in time array (and maybe elsewhere)

### ISSUE THREAD

**Issue by seth-olsen** [sxs-collaboration/gwsurrogate#5] opened 2020-05-05 11:15 UTC
I first noticed that when I called the precessing surrogate with dt=0.001 (units='mks'), only one value was being returned in the waveform array. After thoroughly checking that I was giving the intended values for all the other parameters, I still got this result, so I tried calling the model without specifying dt, and I noticed that the total waveform length was less than 0.001 seconds. Then I started calling it with the exact same parameters several times in succession, and I noticed that every new time I call it with the same parameters,  the total waveform duration T = t[-1] - t[0] goes down by orders of magnitude. Here is an example:

from gwsurrogate import LoadSurrogate
SUR_PRE = LoadSurrogate('NRSur7dq4')

t1, wf1, dyn1 =  SUR_PRE(1, [0.05, 0.0, 0.3], [0, 0.01, -0.1], M=150, f_ref=0, dt=None, \
                            inclination=None, phi_ref=None, ellMax=None, f_low=0, units='mks', dist_mpc=1, \
                            skip_param_checks=True, df=None, freqs=None, times=None, \
                            mode_list=None, precessing_opts=None, tidal_opts=None, \
                            par_dict=None, taper_end_duration=None)
print(t1[-1] - t1[0])

If I call this second block of code 5 times in succession, here are the outputs:
3.250824076870587
0.0024017857224370586
1.774496103171364e-06
1.3110396946548902e-09
9.686271375231078e-13
7.156446409452046e-16

This will keep going indefinitely, each time dividing by exactly
0.0007388236538315364. 
Further, it doesn't matter what parameters I use or what I call the variables. The overall scale of the time array continues to decrease by exactly this factor even if I  call it 5 different times with 5 different sets of parameters and assign the output to 5 different sets of variable names. It also doesn't matter whether or not I specify ellMax and/or the orientation angles. 

When I restart the kernel, the cycle resets. For the first call, the waveform looks reasonable, then for the second call, it looks like it has been zoomed in, and for the third call, it zooms in again. From the fourth call onward, the plot stays the same as after the third call except that the time axis scale is multiplied by a factor of 0.0007388236538315364 with each successive call to SUR_PRE.

It seems that there is somewhere in the generator where the previous calls by the current python kernel are saving information and doing something like
total_time *= 0.0007388236538315364

**Comment by vijayvarma392** [comment] 2020-05-05 20:44
Hi @seth-olsen, I am able to reproduce this. This is very strange and I feel like I should have run into this by now, will dig a little bit and see what's causing this.

**Comment by duetosymmetry** [comment] 2020-05-05 21:51
To me this smells like a variable which was intended to have a local scope and be reset each time a function is entered, but its lifetime was longer than expected. For example, a function's default argument values can actually be objects that get mutated, [simple explanation here](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments)

**Comment by vijayvarma392** [comment] 2020-05-06 23:31
@duetosymmetry, yes that is what I suspected as well and indeed it turned out to be true. This is now fixed in https://github.com/sxs-collaboration/gwsurrogate/pull/6.

@seth-olsen, will let you know once this is merged, and pypi-ed and conda-forge-ed.

**Closed** 2020-05-07 00:37 UTC

**Comment by vijayvarma392** [comment] 2020-05-07 19:39
@seth-olsen: if you try the newly released gwsurrogate version 1.0.4, this issue should go away.

**Comment by sfield17** [comment] 2020-05-07 19:42
PS should be live on conda in a few minutes. I'm waiting for the automated
conda message to approve the PR.
